#!/bin/bash

KERNEL="$(uname -s)"
ARCH="$(uname -m)"

OS=""
if [ "${KERNEL}" == "Darwin" ]; then
  OS="macos"
elif [ "${KERNEL}" == "Linux" ]; then
  TESTOS=$(cat /etc/os-release | grep -w "ID" | cut -d '=' -f2 | tr -d '"')
  case $TESTOS in
    alpine)
      OS="alpine"
    ;;
    debian)
      OS="debian"
    ;;
    fedora | rhel)
      OS="fedora"
    ;;
    ubuntu | pop | linuxmint)
      OS="ubuntu"
    ;;
    *)
      OS="linux"
    ;;
  esac
else
  OS="${KERNEL}"
fi

echo "${OS}_${ARCH}"
