[options]
# Misc options
#UseSyslog
#Color
#NoProgressBar
#TotalDownload
CheckSpace
#VerbosePkgLists
DisableDownloadTimeout

# PGP signature checking
#SigLevel = Optional
LocalFileSigLevel = Optional TrustAll
#RemoteFileSigLevel = Optional

[pspdev]
SigLevel = Optional TrustAll
Server = https://pspdev.github.io/psp-packages/
