#!/bin/bash

## Make sure PSPDEV is set
if [ -z "${PSPDEV}" ]; then
    export PSPDEV=/usr/local/pspdev
fi
## Export makepkg variables
export PACMAN=psp-pacman

## Run makepkg
if which "makepkg" >/dev/null 2>&1; then
    export MAKEPKG_CONF="${PSPDEV}/share/pacman/etc/makepkg.conf"
    makepkg -p PSPBUILD "$@"
else
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PSPDEV}/share/pacman/lib/x86_64-linux-gnu
    "${PSPDEV}/share/pacman/bin/makepkg" "$@"
fi
