#!/bin/bash

## Make sure PSPDEV is set
if [ -z "${PSPDEV}" ]; then
    export PSPDEV=/usr/local/pspdev
fi

if [ ! -d "${PSPDEV}" ]; then
    echo "${PSPDEV} does not exist"
    exit 1
fi

## Use sudo if the current user doesn't own $PSPDEV
if ! touch "${PSPDEV}" >/dev/null 2>&1; then
    ## And only when not using the T or Q option
    if ! [[ $1 = -@(T|Q|V|h)*([[:alpha:]]) ]] && !  [[ $1 = --@(deptest|query|help|version)*([[:alpha:]]) ]]; then
        sudo "$0" "$@"
        exit $?
    fi
fi

## Add the directory with pacman's binaries to the start of the PATH
export PATH="${PSPDEV}/share/pacman/bin:${PATH}"

## Run pacman
pacman "$@"
